### ISSUE TITLE
Bump paper-api to 1.21

### ISSUE THREAD

**Issue by mzcydev** [ConnorChickenway/stella#3]
Hello,

could you bump the paper-api to 1.21 for working up to 1.21?
If not, provide a reason please.

Thanks!

**Comment by ConnorChickenway** [comment]
Hi, I made an update and it now supports Paper 1.21

![2024-09-15_16 54 32](https://github.com/user-attachments/assets/ed84f649-afd5-4957-bc7f-595988bcb65d)
